### ISSUE TITLE
Directory traversal bug

### ISSUE THREAD

**Issue by psychon** [MuffinMedic/znc-weblog#1]
I'll just mention two URLs:
```
http://localhost:12345/mods/global/weblog/raw?dir=../../../configs/znc.conf
http://localhost:12345/mods/global/weblog/raw?dir=../../../../../../etc/passwd
```
For handling this, I suggest using `CDir::CheckPathPrefix`:
```c
    // Check if sPath + "/" + sAdd (~/ is handled) is an absolute path which
    // resides under sPath. Returns absolute path on success, else "".
    static CString CheckPathPrefix(const CString& sPath, const CString& sAdd,
                                   const CString& sHomeDir = "");
```
(So you'd need something like `CheckPathPrefix(base, dir)`; this function returns an empty string if the result is outside of `base`)

**Comment by MuffinMedic** [comment]
Thanks @psychon ! Can you submit a PR with the fixes for this please?

**Comment by lrstanley** [comment]
See PR https://github.com/MuffinMedic/znc-weblog/pull/2 for a fix for this. It tries to enforce the base path, and enforces normalization on the user supplied path (turning `../` into the proper folders, etc.)

I don't use this module, however I also noticed a few other issues which could be addressed.

Running 1.6.5, I am not seeing the errors thrown by this module. For one, when I didn't put `tmpl` in `weblog` properly, it had just shown a red bar with no error, regardless of the theme used:

![](https://i.imgur.com/6rP8Hlm.png)

Is the method you are using to display errors functional for the latest version of ZNC?

Lastly, on dark themes, due to the white color of the logs within your template, you simply cannot see logs unless you highlight them:

![](https://i.imgur.com/wwcGvRg.png)

v.s.

![](https://i.imgur.com/RwU9YYL.png)

**Comment by selurvedu** [comment]
@lrstanley I already have a proposed fix for dark themes (and many other minor changes), give me a few days to get it ready for being published.
